  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="jquery.gridalicious.min.js"></script>
  <script type="text/javascript" src="jquery.jstwitter.js"></script>
  <script type="text/javascript">
  $(function () {
      // start jqtweet!
      JQTWEET.loadTweets();
  });
  </script>

  <script type="text/javascript">
var gaJsHost = (("https:" ==  document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript  src='" + gaJsHost + "google-analytics.com/ga.js'  type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try{
var pageTracker = _gat._getTracker("UA-44449664-1");
pageTracker._trackPageview();
} catch(err) {}</script>

  <footer>


    <nav id="footernav">
      <div class="footercol">
        <div class="innercol">
        <h4>CONTACT US</h4>
        <a href="http://www.twitter.com/AusPollieTweets" target="_blank"><span class="footericons" aria-hidden="true" data-icon="t">&nbsp;&nbsp;Twitter</span></a> <span class="screen-reader-text">Twitter</span>
        <br>
        <br>
        <a href="contact.php"><span class="footericons" aria-hidden="true" data-icon="c">&nbsp;&nbsp;E-mail</span></a> <span class="screen-reader-text">E-mail</span>
        <br>
        <br>
        <p>Also by Rebecca Cordingley:</p>
        <div class="contact_my_mp_widget">
          <div class="contact_my_mp_container">
             <div class="contact_my_mp_link"><a href="http://www.contactmymp.com" target="_blank">Contact My<br>MP Australia</a></div>
             <div class="contact_my_mp_logo"><img src="images/logo.png"></div>
          </div>
          <form id="select_politician" action="http://www.contactmymp.com/select" method="post">
             <label for="postcode">My Postcode:</label>
             <br>
             <input type='number' name='postcode' id='postcode' maxlength='4' placeholder='&#xf041;'>
             <input type='submit' id='submit' name='submit' value="Go">
          </form>
       </div>
      </div>
      </div>
      <div class="desktopfootercol">
        <div class="innercol">
        <h4>HOUSES</h4>
        <ul>
          <li><a href="fed-lower-house.php">Federal Lower House</a></li>
          <li><a href="fed-upper-house.php">Federal Upper House</a></li>
          <li><a href="act.php">Australian Capital Territory Parliament</a></li>
          <li><a href="nsw-lower-house.php">New South Wales Lower House</a></li>
          <li><a href="nsw-upper-house.php">New South Wales Upper House</a></li>
          <li><a href="nt.php">Northern Territory Parliament</a></li>
          <li><a href="qld.php">Queensland Parliament</a></li>
        </ul>
      </div>
      </div>
    </div>
      <div class="desktopfootercol">
        <div class="innercol">
        <h4>HOUSES cont...</h4>
        <ul>
          <li><a href="sa-lower-house.php">South Australia Lower House</a></li>
          <li><a href="sa-upper-house.php">South Australia Upper House</a></li>
          <li><a href="tas-lower-house.php">Tasmania Lower House</a></li>
          <li><a href="tas-upper-house.php">Tasmania Upper House</a></li>
          <li><a href="vic-lower-house.php">Victoria Lower House</a></li>
          <li><a href="vic-upper-house.php">Victoria Upper House</a></li>
          <li><a href="wa-lower-house.php">Western Australia Lower House</a></li>
          <li><a href="wa-upper-house.php">Western Australia Upper House</a></li>
        </ul>
      </div>
      </div>

    </nav>
  <div id="copyright">&copy; 2013 pollietweets.com</div>


  </footer>

	</body>
</html>
