
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<LINK REL="apple-touch-icon-precomposed" href="http://www.pollietweets.com/images/apple-touch-icon.jpg" />
		<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>
		<script type='text/javascript' src='menu_jquery.js'></script>
		<link rel="icon" type="image/x-icon" href="favicon.ico">
		<link rel="stylesheet" href="style.css" type="text/css"/>

		<!--[if lt IE 9]>
		<script src="dist/html5shiv.js"></script>
		<![endif]-->
		<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>

<script type="text/javascript">
	      $(document).ready(function(){
	        $(".submenu").hover(function() {
	          $(this).stop().animate({opacity: "0.85"}, 'slow');
	        },
	        function() {
	          $(this).stop().animate({opacity: "1"}, 'slow');
	        });
	      });
	    </script>

	</head>
	<body>
		<?php
		include('php/common.php'); ?>
