<!-- Desktop Menu -->
        <nav id="bar">
            <ul id="nav">
                <li>
                    <a href="#">FED</a>
                    <ul>
                        <li class="orange submenu">
                            <a href="fed-lower-house.php">House of Representatives</a>
                        </li>
                        <li class="orange submenu">
                            <a href="fed-upper-house.php">Senate</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">ACT</a>
                    <ul>
                        <li class="red submenu">
                            <a href="act.php">Legislative Assembly</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">NSW</a>
                    <ul>
                        <li class="purple submenu">
                            <a href="nsw-lower-house.php">Legislative Assembly</a>
                        </li>
                        <li class="purple submenu">
                            <a href="nsw-upper-house.php">Legislative Council</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">NT</a>
                    <ul>
                        <li class="blue submenu">
                            <a href="nt.php">Legislative Assembly</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">QLD</a>
                    <ul>
                        <li class="green submenu">
                            <a href="qld.php">Legislative Assembly</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">SA</a>
                    <ul>
                        <li class="red submenu">
                            <a href="sa-lower-house.php">House of Assembly</a>
                        </li>
                        <li class="red submenu">
                            <a href="sa-upper-house.php">Legislative Council</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">TAS</a>
                    <ul>
                        <li class="purple submenu">
                            <a href="tas-lower-house.php">House of Assembly</a>
                        </li>
                        <li class="purple submenu">
                            <a href="tas-upper-house.php">Legislative Council</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">VIC</a>
                    <ul>
                        <li class="blue submenu">
                            <a href="vic-lower-house.php">Legislative Assembly</a>
                        </li>
                        <li class="blue submenu">
                            <a href="vic-upper-house.php">Legislative Council</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">WA</a>
                    <ul>
                        <li class="green submenu">
                            <a href="wa-lower-house.php">Legislative Assembly</a>
                        </li>
                        <li class="green submenu">
                            <a href="wa-upper-house.php">Legislative Council</a>
                        </li>
                    </ul>
                </li>

                <li>
            
                    <a href="http://www.twitter.com/AusPollieTweets" target="_blank">
                        <span class="contacticons" aria-hidden="true" data-icon="t"></span>
                        </a> </span>
                        <span class="screen-reader-text">Twitter</span>
                </li>
             </ul>
        </nav>

        <!-- Mobile Menu -->
        <nav id='mobnav'>
            <ul>
                <li class="has-sub">
                    <a href='#'><span>Federal</span></a>
                    <ul>
                        <li class="orange">
                            <a href='fed-lower-house.php'><span>House of Representatives</span></a>
                        </li>
                        <li class="orange">
                            <a href='fed-upper-house.php'><span>Senate</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href='#'><span>Australian Capital Territory</span></a>
                    <ul>
                        <li class="red">
                            <a href='act.php'><span>Legislative Assembly</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>New South Wales</span></a>
                    <ul>
                        <li class="purple">
                            <a href="nsw-lower-house.php"><span>Legislative Assembly</span></a>
                        </li>
                        <li class="purple">
                            <a href="nsw-upper-house.php"><span>Legislative Council</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>Northern Territory</span></a>
                    <ul>
                        <li class="blue">
                            <a href="nsw-lower-house.php"><span>Legislative Assembly</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="#"><span>Queensland</span></a>
                    <ul>
                        <li class="green">
                            <a href="qld.php"><span>Legislative Assembly</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>South Australia</span></a>
                    <ul>
                        <li class="red">
                            <a href="sa-lower-house.php"><span>House of Assembly</span></a>
                        </li>
                        <li class="red">
                            <a href="sa-upper-house.php"><span>Legislative Council</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>Tasmania</span></a>
                    <ul>
                        <li class="purple">
                            <a href="tas-lower-house.php"><span>House of Assembly</span></a>
                        </li>
                        <li class="purple">
                            <a href="tas-upper-house.php"><span>Legislative Council</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>Victoria</span></a>
                    <ul>
                        <li class="blue">
                            <a href="vic-lower-house.php"><span>Legislative Assembly</span></a>
                        </li>
                        <li class="blue">
                            <a href="vic-upper-house.php"><span>Legislative Council</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="#"><span>Western Australia</span></a>
                    <ul>
                        <li class="green">
                            <a href="wa-lower-house.php"><span>Legislative Assembly</span></a>
                        </li>
                        <li class="green">
                            <a href="wa-upper-house.php"><span>Legislative Council</span></a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a href="http://www.twitter.com/AusPollieTweets" target="_blank"><span>PollieTweets on Twitter</span></a>
                </li>
                <li class="has-sub">
                    <a href="contact.php"><span>Contact Us</span></a>
                </li>
            </ul>
            <div id="pull">
                <div class="pullitem">
                    <span aria-hidden="true" data-icon="n">&nbsp;&nbsp;Menu</span> <span class="screen-reader-text">Menu</span>
                </div>
            </div>
        </nav>